# Generated by Django 4.2.9 on 2024-02-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stripeorders',
            fields=[
                ('StripeOrderNum', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('StripeOrderUserName', models.CharField(max_length=50)),
                ('StripeShipStatus', models.CharField(max_length=10)),
            ],
        ),
    ]
