# Generated by Django 4.2.9 on 2024-03-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stripeorders',
            fields=[
                ('stripe_order_num', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stripe_order_email', models.CharField(max_length=50)),
                ('stripe_ship_status', models.CharField(max_length=10)),
                ('stripe_shipping_address', models.CharField(default='DEFAULT', max_length=255)),
                ('stripe_receipt_url', models.CharField(default='DEFAULT', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='stripeshoppingcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item_username', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('adjustable_quantity', models.CharField(max_length=50)),
            ],
        ),
    ]
