# Generated by Django 4.2.9 on 2024-03-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeshoppingcart',
            name='quantity',
            field=models.IntegerField(max_length=4),
        ),
    ]
