# Generated by Django 4.2.9 on 2024-02-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripeorders',
            old_name='StripeOrderNum',
            new_name='stripe_order_num',
        ),
        migrations.RenameField(
            model_name='stripeorders',
            old_name='StripeOrderUserName',
            new_name='stripe_order_username',
        ),
        migrations.RenameField(
            model_name='stripeorders',
            old_name='StripeShipStatus',
            new_name='stripe_ship_status',
        ),
    ]
