# Generated by Django 4.2.9 on 2024-03-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_rename_stripeordernum_stripeorders_stripe_order_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stripshoppingcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item_username', models.CharField(max_length=50)),
                ('cart_item_priceid', models.CharField(max_length=50)),
                ('cart_item_qty', models.CharField(max_length=4)),
            ],
        ),
    ]
